name: Build Debian package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install build dpendencies
    - name: Install build dependencies
      run: sudo apt install -y sed g++ pkg-config libnotify-dev

    # Build the package
    - name: Build package
      run: make build
    # Test the package
    - name: Test package
      run: make test
    # Install the package
    - name: Install package
      run: sudo make install
    # Uninstall the package
    - name: Uninstall package
      run: sudo make uninstall
    # Cleanup
    - name: Cleanup package
      run: make clean

    # Build the Debian package
    - name: Build Debian package
      run: sudo make dist
    # Install the built Debian package
    - name: Install Debian package
      run: sudo dpkg -i dist/kernel-notify-*.deb
    # Cleanup
    - name: Cleanup Debian package
      run: sudo make clean
