name: Build kernel-notify and the Debian package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Install build dependencies
    - name: Install build dependencies
      run: sudo apt install -y sed g++ pkg-config libnotify-dev

    # Build the package
    - name: Build package
      run: make build
    # Test the package
    - name: Test package
      run: make test
    # Install the package
    - name: Install package
      run: sudo make install
    # Uninstall the package
    - name: Uninstall package
      run: sudo make uninstall
    # Cleanup
    - name: Cleanup package
      run: make clean

    # Build the Debian package
    - name: Build Debian package
      run: sudo make dist
    # Install the built Debian package
    - name: Install Debian package
      run: sudo dpkg -i dist/kernel-notify-*.deb
    # Cleanup
    - name: Cleanup Debian package
      run: sudo make clean
